
spring:
  application:
    name: "auth-service"
  datasource:
    url: jdbc:sqlserver://DESKTOP-0O190JQ\SQLEXPRESS:1433;databaseName=appuser_ms;encrypt=true;trustServerCertificate=true
    username: sa
    password: Adteamkingp3
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23li8Mh5yaM3O75v8W
            clientSecret: a860ea01b0c331f802abec9b36d6c270c1a26e40
            redirectUri: http://localhost:8080/oauth2/callback/github
            scope:
              - user:email
              - read:user

server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 3600000
  cors:
    allowedOrigins: http://localhost:8080,http://localhost:5173
  oauth2:
    authorizedRedirectUris:
      - http://localhost:5173/oauth2/redirect