spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from:
      email: ${MAIL_USERNAME}
    protocol: smtp
    tls: true
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
      mail.smtp.starttls.required: true

