
spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        # LIFE_TASKS-SERVICE
        - id: lifetask-service
          uri: lb://LIFETASK-SERVICE
          predicates:
            - Path=/api/life/tasks/**
        # AUTH-SERVICE
        - id: user-service-auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: user-service-manager
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/user/**
        # PROJECT-SERVICE
        - id: project-service
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path=/api/project/**

      discovery:
        locator:
          enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "apigateway-server"
    description: "Calendarize Application"
    version: "1.0.0"
server:
  port: 8071